# Generated by Django 5.1.4 on 2025-10-14 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAISES',
            fields=[
                ('ID_PAIS', models.IntegerField(primary_key=True, serialize=False)),
                ('PAIS', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='REGIONES',
            fields=[
                ('ID_REGION', models.IntegerField(primary_key=True, serialize=False)),
                ('REGION', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TIPOS_DOCUMENTOS',
            fields=[
                ('ID_TIPO_DOCUMENTO', models.IntegerField(primary_key=True, serialize=False)),
                ('TIPO_DOCUMENTO', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TIPOS_USUARIOS',
            fields=[
                ('ID_TIPO_USUARIO', models.IntegerField(primary_key=True, serialize=False)),
                ('TIPO_USUARIO', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DOCUMENTOS',
            fields=[
                ('ID_DOCUMENTO', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_DOCUMENTO', models.CharField(blank=True, max_length=20, null=True)),
                ('FECHA_INGRESO', models.DateField(blank=True, null=True)),
                ('ID_TIPO_DOCUMENTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipos_documentos')),
            ],
        ),
        migrations.CreateModel(
            name='USUARIOS',
            fields=[
                ('ID_USUARIO', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_USUARIO', models.CharField(blank=True, max_length=15, null=True)),
                ('APELLIDO_USUARIO', models.CharField(blank=True, max_length=15, null=True)),
                ('TELEFONO', models.IntegerField(blank=True, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('DIRECCION', models.CharField(blank=True, max_length=30, null=True)),
                ('ID_PAIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paises')),
                ('ID_REGION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.regiones')),
                ('ID_TIPO_USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipos_usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='HISTORIAL_CAMBIOS',
            fields=[
                ('ID_HISTORIAL', models.IntegerField(primary_key=True, serialize=False)),
                ('FECHA_MODIFICACION', models.DateField(blank=True, null=True)),
                ('FECHA_ELIMINAR', models.DateField(null=True)),
                ('ID_DOCUMENTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.documentos')),
                ('ID_USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='documentos',
            name='ID_USUARIO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios'),
        ),
    ]
