# Generated by Django 5.1.4 on 2025-10-17 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_paises_regiones_tipos_documentos_tipos_usuarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id_documento_tipo', models.AutoField(db_column='ID_DOCUMENTO_TIPO', primary_key=True, serialize=False)),
                ('documento_tipo', models.CharField(blank=True, db_column='DOCUMENTO_TIPO', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(db_column='ID_PAIS', primary_key=True, serialize=False)),
                ('pais', models.CharField(blank=True, db_column='PAIS', max_length=50)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(db_column='ID_REGION', primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, db_column='REGION', max_length=50)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTipo',
            fields=[
                ('id_usuario_tipo', models.AutoField(db_column='ID_USUARIO_TIPO', primary_key=True, serialize=False)),
                ('usuario_tipo', models.CharField(blank=True, db_column='USUARIO_TIPO', max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
            },
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='ID_TIPO_DOCUMENTO',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='ID_USUARIO',
        ),
        migrations.RemoveField(
            model_name='historial_cambios',
            name='ID_DOCUMENTO',
        ),
        migrations.RemoveField(
            model_name='historial_cambios',
            name='ID_USUARIO',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ID_PAIS',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ID_REGION',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='ID_TIPO_USUARIO',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_pais',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_region',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_apellido',
            field=models.CharField(blank=True, db_column='USUARIO_APELLIDO', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_nombre',
            field=models.CharField(blank=True, db_column='USUARIO_NOMBRE', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, db_column='DIRECCION', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, db_column='EMAIL', max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, db_column='TELEFONO', max_length=20),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(db_column='ID_DOCUMENTO', primary_key=True, serialize=False)),
                ('documento_nombre', models.CharField(blank=True, db_column='DOCUMENTO_NOMBRE', max_length=100)),
                ('archivo', models.FileField(blank=True, db_column='ARCHIVO', null=True, upload_to='documentos/')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_column='FECHA_INGRESO')),
                ('usuario', models.ForeignKey(db_column='ID_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
                ('documento_tipo', models.ForeignKey(blank=True, db_column='ID_DOCUMENTO_TIPO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.documentotipo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='ID_PAIS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pais'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.ForeignKey(blank=True, db_column='ID_REGION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_tipo',
            field=models.ForeignKey(blank=True, db_column='ID_USUARIO_TIPO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuariotipo'),
        ),
        migrations.DeleteModel(
            name='TIPOS_DOCUMENTOS',
        ),
        migrations.DeleteModel(
            name='DOCUMENTOS',
        ),
        migrations.DeleteModel(
            name='HISTORIAL_CAMBIOS',
        ),
        migrations.DeleteModel(
            name='PAISES',
        ),
        migrations.DeleteModel(
            name='REGIONES',
        ),
        migrations.DeleteModel(
            name='TIPOS_USUARIOS',
        ),
        migrations.DeleteModel(
            name='USUARIOS',
        ),
    ]
